version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY:-"insira_sua_chave_groq_aqui"}
      - DB_HOST=postgres
      - DB_NAME=sre_vector_manual
      - DB_USER=db_admin
      - DB_PASSWORD=admin_password
    depends_on:
      - postgres

  mock-generator:
    image: python:3.12-slim
    command: sh -c "pip install prometheus_client requests && python /app/mock_generator.py"
    volumes:
      - ./mock_generator.py:/app/mock_generator.py
    ports:
      - "8001:8001"
    depends_on:
      - loki

  postgres:
    image: ankane/pgvector:v0.5.1
    environment:
      POSTGRES_DB: sre_vector_manual
      POSTGRES_USER: db_admin
      POSTGRES_PASSWORD: admin_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/dashboards/sre_dashboard.json
    volumes:
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - ./grafana/dashboards:/etc/grafana/dashboards
    depends_on:
      - prometheus
      - loki

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  loki:
    image: grafana/loki:latest
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

volumes:
  postgres_data:

